"use strict";
const productPrice = 12;
let myname = "luis";
let myname2 = "david";
//myname = true;
//myname2 = 12;
myname = "suquillo";
(() => {
    let myProductName = "lapto AZUL";
    let myProductPrice = 500;
    let myProductName2 = "lapto BLANCA";
    let myProductPrice2 = 600;
    let myProductName3 = "lapto GRIS";
    let myProductPrice3 = 700;
    console.log(myProductName, myProductName2, myProductName3);
    console.log(myProductPrice, myProductPrice2, myProductPrice3);
    myProductName = "celular xiaomi negro";
    myProductName.toLowerCase();
    console.log(myProductName);
    myProductPrice.toFixed();
    myProductPrice = 600;
    myProductName2 = "celulat tec spark";
    console.log(myProductName2);
    console.log(myProductPrice);
})();
